repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.5
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: "\\.(py)$"
    args: [--settings-path=pyproject.toml]
